# Generated by Django 4.1.4 on 2022-12-28 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('creted_date', models.DateTimeField(auto_created=True)),
                ('seat_number', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('seat_discription', models.CharField(max_length=1000)),
                ('slot1', models.IntegerField()),
                ('slot2', models.IntegerField()),
                ('slot3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AllBooking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('Seat_number', models.IntegerField()),
                ('Slot', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
