# Generated by Django 4.1.4 on 2022-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('creted_date', models.DateTimeField(auto_created=True)),
                ('seat_number', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('seat_discription', models.CharField(max_length=1000)),
                ('slot1', models.BooleanField(default=True)),
                ('slot2', models.BooleanField(default=True)),
                ('slot3', models.BooleanField(default=True)),
            ],
        ),
    ]
