# Generated by Django 4.1.4 on 2022-12-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbooking',
            name='booking_date',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
