# Generated by Django 4.1.4 on 2022-12-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('Seat_number', models.IntegerField()),
                ('Slot', models.CharField(max_length=1)),
            ],
        ),
    ]
