# Generated by Django 4.1.4 on 2022-12-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookings',
            new_name='Booking',
        ),
    ]
