# Generated by Django 4.1.4 on 2022-12-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_allbooking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooking',
            name='userID',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
