# Generated by Django 4.1.4 on 2022-12-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_bookings_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='AllBooking',
        ),
    ]
