# Generated by Django 4.1.4 on 2022-12-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_booking_allbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooking',
            name='Slot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='slot1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='slot2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='slot3',
            field=models.IntegerField(),
        ),
    ]
